#!/bin/sh
root_project=smx-gcloud-cis-abdullah
command_topic=smx-command
command_subscription=smx-command-subscription
log_topic=log-aggregation
log_topic_url=projects/$root_project/topics/$log_topic
root_report=smx-cis-reports-abdullah
root_system=smx-cis-root-abdullah/system
root_config=smx-cis-root-abdullah/config

usage ()
{
  echo 'Usage : schdCheck -w <working-dir>'
  exit
}

while [ "$1" != "" ]; do
case $1 in
        -w )           shift
                       WDIR=$1
                       ;;
        * )            ETC=$1
    esac
    shift
done

if [ "$WDIR" = "" ]
then
    WDIR=$(uuidgen)
    DEL=Yes
    mkdir -p $WDIR
fi

if [ "$WDIR" = "" ]
then
    usage
fi

rm -rf $WDIR/*

# ware are doing the GCP storage only
gsutil ls -L gs://smx-cis-root/config/*/storage.config > $WDIR/allconfig
gsutil ls gs://$root_system/*/storage > $WDIR/allsysdir

#python scheduled_check.py -p $root_project -w $WDIR -s "$root_system" -c "$root_config" -t "$log_topic_url"

python scheduled_check.py -p $root_project -w $WDIR -s "$root_system" -c "$root_config"

if [ "$DEL" = "Yes" ]
then
  touch $WDIR/.lastcheck
  gsutil cp $WDIR/.lastcheck gs://$root_system/.config/
  gsutil cp $WDIR/.lastcheck gs://$root_config/.config/
  rm -rf $WDIR
fi
