resources:
- name: ubuntu
  type: compute.v1.instance
  properties:
    zone: us-east4-c
    machineType: zones/us-east4-c/machineTypes/n1-standard-1
    disks:
    - deviceName: boot
      type: PERSISTENT
      boot: true
      autoDelete: true
      initializeParams:
        diskSizeGb: '10'
        sourceImage: projects/ubuntu-os-cloud/global/images/ubuntu-1604-xenial-v20180627
    networkInterfaces:
    - network: global/networks/default
    metadata:
      items:
      - key: startup-script
        value: |-
          cd /home/ubuntu
      kind: compute#metadata
    serviceAccounts:
    - email: 323252478117-compute@developer.gserviceaccount.com
      scopes:
      - https://www.googleapis.com/auth/cloud-platform
